name: PR on master
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [12.x]

    # Define Steps
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Make sure we have all branches
      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install environment
        run: |
          rm -rf node_modules && rm -rf dist && rm -rf docs && rm -rf coverage
          npm install
      - name: Run lint
        run: |
          chmod +x ./.github/scripts/run-linting.sh
          ./.github/scripts/run-linting.sh False

      - name: Tests coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          chmod +x ./.github/scripts/run-testing.sh
          ./.github/scripts/run-testing.sh False True $CODECOV_TOKEN
